version: "3.8"

services:
  dbpostgres:
    image: postgres:14.5
    container_name: dbpostgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
      - ./pg_init_scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=passdb
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - ntw
  nginxproxy:
    image: nginx:latest
    container_name: nginxproxy
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    environment:
      - NGINX_PORT=8080
    ports:
      - "8080:8080"
    networks:
      - ntw
    depends_on:
      dbpostgres:
        condition: service_started
  nodejs:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: nodejsimg
    container_name: nodejs
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - ENVIRONMENT=DEV
      - DB_CONFIG=postgres://userdb:passdb@hostdb:5432/postgresdb
    depends_on:
      dbpostgres:
        condition: service_started
    networks:
      - ntw
networks:
  ntw:
    driver: bridge
volumes:
  pgdata:
